### ISSUE TITLE
Possible wrong intent classification

### ISSUE THREAD

**Issue by jesus-seijas-sp** [sebischair/NLU-Evaluation-Corpora#10]
There are some utterances that perhaps does not have the correct intent:

**AskUbuntuCorpus**
- Utterance "_Is there a Document scanning and archiving software?_", is classified as "_None_", perhaps should be classified as "_Software Recommendation_"
- Utterance "_Is it recommended to upgrade to Lubuntu 15.04?_" is classified as "_Software Recommendation_", perhaps should be classified as "_Make Update_"
- Utterance "_On really old Ubuntu 6.06 - How to upgrade_" is classified as "_Software Recommendation_", perhaps should be classified as "_Make Update_"

**WebApplicationsCorpus**
- The utterance "_Good wireframing apps?_" is classified as "_None_", but In my oppinion a better classification can be "_Find Alternative_". Basically if the utterance was "_Good wireframing apps like balsamiq_" this will be clearly a "_Find Alternative_". By ommiting the entity the intent should remain the same.
- The utterance "_What are alternatives to Postini for spam filtering?_" is classified as "_Filter Spam_", perhaps should be classified as "_Find Alternative_"

**Comment by DaBr01** [comment]
For information on how the corpus was labelled please refer to the paper. Many classification tasks (including this) are not unambiguously, therefore it is important to stick to a fixed methodology and we won't change labels.
