### ISSUE TITLE
The entity "StationStart" in ChatbotCorpus.json

### ISSUE THREAD

**Issue by jhihhong** [sebischair/NLU-Evaluation-Corpora#5]
The entity "StationStart" of "how can i get from moosach to quiddestraße?" in ChatbotCorpus.json seems incorrect

**Comment by DaBr01** [comment]
How so? It's:

`
        {
          "entity": "StationStart",
          "start": 5,
          "stop": 5,
          "text": "moosach"
        }
`

and that should be correct.

**Comment by jhihhong** [comment]
I found repeated sentence in

line 546: `{"entity":"StationStart","start":5,"stop":5,"text":"moosach"},`
line 600: `{"entity":"StationStart","start":8,"stop":8,"text":"?"}`

**Comment by DaBr01** [comment]
Indeed, thank you!
