### ISSUE TITLE
Data size for Web Applications Corpus

### ISSUE THREAD

**Issue by 8key** [sebischair/NLU-Evaluation-Corpora#9]
Hey you mentioned that Web Applications Corpus has 100 data sets, but only 89 (30 for train and 59 for test) is included in your json file. Can you explain why there is a difference. 

thanks 

greg

**Comment by DaBr01** [comment]
Thanks for the hint!

This was a mistake in the description which is now fixed. We initially had 100 questions, but only 89 made it into the corpus. More details on why that was the case can be found in the paper ("A label, no matter if intent or entity, was only added to the corpus if the inter-annotator agreement among those confident annotators was 60% or higher. If no intent could be found for a question, satisfying these criteria, this question was not added to the corpus.")

**Comment by 8key** [comment]
Got it

thanks
________________________________
